{{- if .Values.tlsCertificate -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "postfix.fullname" . }}-certificate
  namespace: {{ .Release.Namespace }}
data:
  tls.chain: {{ .Values.tlsCertificateChain | b64enc }}
  tls.crt: {{ .Values.tlsCertificate | b64enc }}
  tls.key: {{ .Values.tlsKey | b64enc }}
{{- end -}}
